all:
  hosts:
    master:
      ansible_host: 89.169.135.199
      ip: 10.0.1.10
      access_ip: 10.0.1.10
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
    node1:
      ansible_host: 89.169.174.106
      ip: 10.0.2.11
      access_ip: 10.0.2.11
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
    node2:
      ansible_host: 84.201.150.246
      ip: 10.0.3.12
      access_ip: 10.0.3.12
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
    teamcity-server:
      ansible_host: 89.169.158.220
      ip: 10.0.1.44
      access_ip: 10.0.1.44
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
    teamcity-agent:
      ansible_host: 51.250.14.105
      ip: 10.0.1.34
      access_ip: 10.0.1.34
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
