
all:
  hosts:
    master:
      ansible_host: 89.169.134.37
      ip: 10.0.1.10
      access_ip: 10.0.1.10
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
    node1:
      ansible_host: 158.160.18.237
      ip: 10.0.2.11
      access_ip: 10.0.2.11
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
    node2:
      ansible_host: 84.252.133.28
      ip: 10.0.3.11
      access_ip: 10.0.3.11
      ansible_user: ubuntu
      ansible_ssh_common_args: "-i /root/.ssh/id_rsa"
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
