{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemFree",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/mapper/centos-root\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}