apiVersion: v1
kind: Service
metadata:
  name: task-svc
spec:
  selector:
    app: task
  ports:
  - port: 9001
    name: nginx
    targetPort: 80
  - port: 9002
    name: multitool
    targetPort: 8080
