---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.66.247
      ansible_user: user

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.13.28
      ansible_user: user

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.86.119
      ansible_user: user
