apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqin
  labels:
    app: main
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: conf
            mountPath: /usr/share/nginx/html
      - image: wbitt/network-multitool
        name: multitool
        imagePullPolicy: IfNotPresent
        env:
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: ng
          - name: HTTPS_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: mt
      volumes:
      - name: conf
        configMap:
          name: conf
