apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: default
spec:
  selector:
    app: main
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    nodePort: 30000
  type: NodePort
